---
# Vagrantfile configuration
  box_ipaddress: "192.168.12.12"
  box_memory: 2048
  box_cpu: 1

# Default settings
  default_user: "vagrant"
  timezone: Europe/Istanbul

# Git config user credentials
  git_user_name: ""
  git_user_email: ""
