# Virtual system configuration
vm:
  ip: "192.168.12.12"
  memory: 2048
  cpu: 1

box:
  name: "juysoft/vagrant-lemp-stack"
  version: "1.0.0"

user: "vagrant"

# Set the name of the VM
machine_name: "vagrantlemp"

# Default timezone
timezone: Europe/Istanbul

# Use vagrant cachier plugin
use_cachier: true

# Ansible provision settings
ansible:
  provision: true
  verbose: false

# Git config user credentials
git:
  user_name: ""
  user_email: ""

# Blackfire settings
blackfire:
  server_id: ""
  server_token: ""

# Debug message for development test
test:
  install: false
  message: "Debug message test"

# Shared project folder test
shared_folder: false
