---
- name: Install configured globally-required packages
  become_user: "{{ composer_home_owner }}"
  shell: >
    COMPOSER_HOME={{ composer_home_path }}
    composer global require {{ item.name }}:{{ item.release | default('@stable') }} --no-progress
    creates={{ composer_home_path }}/vendor/{{ item.name }}
  with_items: composer.global_packages
