---
- name: Set git username
  command: git config --global user.name {{ git.user_name }}
  sudo_user: "{{ user }}"

- name: Set git user email
  command: git config --global user.email {{ git.user_email }}
  sudo_user: "{{ user }}"
